import uuid
from datetime import datetime

from pydantic import BaseModel, field_validator


# ── Request ──────────────────────────────────────────────────────────


class ConversationCreate(BaseModel):
    title: str = "New conversation"


class MessageRequest(BaseModel):
    content: str


# ── Response ─────────────────────────────────────────────────────────


class SourceItem(BaseModel):
    document_id: int
    document_name: str
    page_index: int | None = None
    chunk_index: int | None = None
    content: str
    score: float | None = None


class MessageResponse(BaseModel):
    id: int
    role: str
    content: str
    sources: list[SourceItem] | None = None
    created_at: datetime

    model_config = {"from_attributes": True}

    @field_validator("sources", mode="before")
    @classmethod
    def transform_sources(cls, v):
        """Convert the JSON ``sources`` dict to a list of ``SourceItem``."""
        if isinstance(v, dict):
            raw = v.get("sources", [])
            return [SourceItem(**s) for s in raw] if raw else None
        return v


class ConversationResponse(BaseModel):
    id: uuid.UUID
    title: str
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}


class ConversationDetailResponse(ConversationResponse):
    messages: list[MessageResponse] = []


class ConversationListResponse(BaseModel):
    conversations: list[ConversationResponse]
    total: int


class DeleteResponse(BaseModel):
    message: str


# ── SSE event payloads ──────────────────────────────────────────────


class StreamToken(BaseModel):
    """Sent for each token generated by the LLM."""

    type: str = "token"
    content: str


class StreamSources(BaseModel):
    """Sent once when streaming is complete, with extracted sources."""

    type: str = "sources"
    sources: list[SourceItem]


class StreamError(BaseModel):
    """Sent when an error occurs during streaming."""

    type: str = "error"
    message: str


class StreamDone(BaseModel):
    """Sent when streaming is complete."""

    type: str = "done"
    message_id: int
    content: str
